import Head from "next/head"
import Navbar from '../components/Navbar'
import Blob from '../components/Blob'

export default function About() {

    return (
        <>
            <Head>
                <title>JM | About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <Navbar />
                <section className="section-box">
                    <section className="about-box">
                        <div className="title">About me</div>
                        <p>Hello, my name is Jaloliddin and I am a Frontend Developer. Ever since I was a child, I&apos;ve always dreamt of creating something that is both useful and interesting to people. That&apos;s why I chose to pursue a career in software development.</p>
                        <p>Currently, I am studying at INHA University in Tashkent as a Software Developer. This field is constantly evolving, which means there is always something new to learn and explore.</p>
                        <p>I am excited to see where this journey takes me, and I am committed to working hard and putting in the effort required to achieve my dream of creating something truly amazing and useful for people.</p>
                    </section>

                    <section className="part-box">
                        <div className="title">Skills</div>
                        <div className="skills-box">
                            <div>HTML5</div>
                            <div>CSS3</div>
                            <div>JavaScript</div>
                            <div>React JS</div>
                            <div>Next JS</div>
                            <div>Three JS</div>
                            <div>Figma</div>
                        </div>
                    </section>
                </section>
                <Blob />
            </main>
        </>
    )
}
