import Head from "next/head"
import Navbar from '../components/Navbar'
import Blob from '../components/Blob'

export default function Projects() {

    return (
        <>
            <Head>
                <title>JM | About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <Navbar />
                
                <Blob />
            </main>
        </>
    )
}